### ISSUE TITLE
Can't connect to opensubtitles servers

### ISSUE THREAD

**Issue by krzyk** [emericg/OpenSubtitlesDownload#47]
Since a month I have issue that I can't download any subtitles, each time I get error message that "Unable to reach opensubtitles.org servers!", I can normally download the subtitles using the browser.
Also this app worked 2 months ago. What happened?

**Comment by emericg** [comment]
Hi,
Can you access this address directly in your browser? https://api.opensubtitles.org/xml-rpc
This is the address the app is connecting to.

I believe opensubtitles.org is beeing blocked in some more countries now, so it could be because of that. Solution for this particular problem is to use custom DNS servers like the ones from Cloudfare or Google, or use proxy (but that's more complicated).
Otherwise maybe an update of your python package on your OS, maybe...

Let me know!

**Comment by krzyk** [comment]
OK, it was actually the issue with python that comes from brew in macOS, it doesn't have up to date certificates (I had to add prints for exceptions to see that, might be usefull to have it enabled by default).

**Comment by emericg** [comment]
Ho yes I actually enabled SSL for the osd server url, but that was done back in may.
This is good feedback, what exception did you add in order to make it print? Thanks.
