### ISSUE TITLE
Make the language suffix coherent with --lang argument

### ISSUE THREAD

**Issue by antznin** [emericg/OpenSubtitlesDownload#57]
I'm not sure whether this is intentional or not, but the suffixed language appears to differ from the input language passed through `--lang`.

For example, if `--lang fre` is passed, the result suffix would be `_fr`. This makes the output `srt` hard to use in a script since the output filename of a given language code is non-deterministic. IMO, if `--lang fre` is passed as an argument, `_fre` should be the resulting suffix.

Otherwise, I have a couple other solutions to this problem : 
 - Make `opt_language_suffix` configurable from the cli
 - Make the filename configurable from the cli. ATM, only the output directory is configurable, but not the filename if I'm not mistaken.

Thanks for the script!

**Comment by emericg** [comment]
Yes it was intentional, mostly because I think 2 letter language code looked better. But at the same time the default language code is a 3 letter one, and I agree, it's not really consistent.
I've changed it to use the same language code.
I've also added a -x option to force a language suffix from the CLI.

**Comment by antznin** [comment]
That was quick. Thank you!
