### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ManuLinares** [emericg/OpenSubtitlesDownload#67]
```
>> Unable to reach opensubtitles.org servers!
Search error
```

I can access https://api.opensubtitles.org/xml-rpc and http://api.opensubtitles.org/xml-rpc
I can login with my user, but it fails anyway.

**Comment by emericg** [comment]
Is it working today?
Does it happen on one particular file or all of them?

**Comment by ManuLinares** [comment]
Curious, working on some files (Although it doesn't find subtitles and I do)

> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E02 - Mortynight Run (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E03 - Auto Erotic Assimilation (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E04 - Total Rickall (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E05 - Get Schwifty (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E06 - The Ricks Must Be Crazy (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E07 - Big Trouble in Little Sanchez (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E08 - Interdimensional Cable 2 - Tempting Fate (1080p BluRay x265 Garshasp).mkv
> >> Unable to reach opensubtitles.org servers!
> Search error
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E09 - Look Who's Purging Now (1080p BluRay x265 Garshasp).mkv
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E10 - The Wedding Squanchers (1080p BluRay x265 Garshasp).mkv
> >> Unable to reach opensubtitles.org servers!
> Search error
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E01 - A Rickle in Time (1080p BluRay x265 Garshasp).mkv
>

**Comment by ManuLinares** [comment]
I renamed the files to this and now works
```
'Rick and Morty - BluRay - S01E01.mkv'
'Rick and Morty - BluRay - S01E02.mkv'
'Rick and Morty - BluRay - S01E03.mkv'
'Rick and Morty - BluRay - S01E04.mkv'
'Rick and Morty - BluRay - S01E05.mkv'
'Rick and Morty - BluRay - S01E06.mkv'
'Rick and Morty - BluRay - S01E07.mkv'
'Rick and Morty - BluRay - S01E08.mkv'
'Rick and Morty - BluRay - S01E09.mkv'
'Rick and Morty - BluRay - S01E10.mkv'
```

I guess the api didn't like some ascii chars?

**Comment by emericg** [comment]
No I think there are just two issues here. The _Unable to reach opensubtitles.org servers_ is probably just a temporary error, because, as stated, opensubtitles.org servers couldn't be reached. That happens at times, they are usually very busy servers...

_No subtitles found_ is also what it means. This script search for subtitles using file hash, then file name. In your case both failed (your files haven't been matched with a subtitles on the website, and the names are ambiguous). When you renamed them, searching with the filename became more straightforward.

So all in all, I think this isn't really a bug. You can confirm that, if you try again on a file that previously failed, is it working now?

**Comment by ManuLinares** [comment]
1. You should try to force only filename search with 
`OpenSubtitlesDownload.py -s filename "Rick and Morty (2013) - S02E01 - A Rickle in Time (1080p BluRay x265 `Garshasp).mkv".
2. try this filename "Rick and Morty (2013) - S02E01 - A Rickle in Time (1080p BluRay x265 Garshasp).mkv" without quotes

> >> Unable to reach opensubtitles.org servers!
> Search error
> >> No subtitles found for this video:
> Rick and Morty (2013) - S02E01 - A Rickle in Time (1080p BluRay x265 Garshasp).mkv

**Comment by emericg** [comment]
Regarding the first one, it's probably best if you rename your files yourself directly ^^
The second point is just because the login and subtitles search are retried once if the server doesn't answer (because these servers are overloaded a lot). So in your case the first search failed, the other one succeeded.
