### ISSUE TITLE
Search by hash do not work

### ISSUE THREAD

**Issue by rdmartins** [emericg/OpenSubtitlesDownload#92]
Hello,

The search by hash is not working, for a long time now.
I used the script for years on Gentoo, on KDE Plasma, and I tried to figure it out why it is not working, but I had no success.
Now I'm using Gnome on Fedora, but the issue persists.

Do you have any idea of what can be causing this?
I can fix it myself and send you a pull request, but I could not solve it by myself.
![image](https://user-images.githubusercontent.com/13852370/191519381-1b1cbe28-de26-4e68-af3d-c4240116b27a.png)
Rafael D Martins.

**Comment by emericg** [comment]
Serch by hash does work as intended I guess (try with 'older' files), but I think the problem is that no one is uploading hashes anymore... and so (most) recent titles just have to be searched with filenames.
It doesn't look like the hash format changed, even with the new OpenSubtitles API, so it's probably just a general lack of hash uploads.

**Comment by rdmartins** [comment]
Oh, I see. The software is okay, the issue is with OpenSubtitles that don't have the hashes on their end.

That explain why I could not figure it out, then.

Anyway, thank you.
